### ISSUE TITLE
Client Stability

### ISSUE THREAD

**Issue by TAGau61** [GamingCoookie/dv-multiplayer-continued#4] opened 2022-03-10 04:39 UTC
**Describe the bug**
Consistant Client crashing.

**To Reproduce**
1. Connect to host
2. Go to Station office as client and pick a job and start
3. during job the client will hard crash with the need of task manager to kill

**Expected behavior**
client will hard crash with the need of task manager to kill

**Desktop (please complete the following information):**
 - OS: Windows 10 pro 21H2 Build 19044.1526
 - Mod Version: Multiplayer Mod Continued 1.3.5

**Comment by GamingCoookie** [comment] 2022-03-11 06:57
Thank you for reporting this issue. I don't have much time, 
I'll first have to finish this [pull request](https://github.com/GamingCoookie/dv-multiplayer-continued/pull/3) I have open, then I hope to figure out what happens with you. :)

**Comment by GamingCoookie** [comment] 2022-03-12 14:04
I sadly could not reproduce this crash in my testing. I know what you could do though if it happens again:

There is a very detailed log file in C:/Users/(your user)/AppData/LocalLow/Altfuture/DerailValley, just send the contents of that next time. But so I will close this issue now.

**Closed by GamingCoookie** 2022-03-12 14:04 UTC
Labels: bug
